// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToCluster(arg1) {
  return window['go']['main']['App']['ConnectToCluster'](arg1);
}

export function DescribeGrpcMethod(arg1, arg2, arg3) {
  return window['go']['main']['App']['DescribeGrpcMethod'](arg1, arg2, arg3);
}

export function DisconnectFromCluster() {
  return window['go']['main']['App']['DisconnectFromCluster']();
}

export function GenerateRequestSkeleton(arg1, arg2) {
  return window['go']['main']['App']['GenerateRequestSkeleton'](arg1, arg2);
}

export function GenerateSampleRequest(arg1, arg2) {
  return window['go']['main']['App']['GenerateSampleRequest'](arg1, arg2);
}

export function GetAccessibleNamespaces() {
  return window['go']['main']['App']['GetAccessibleNamespaces']();
}

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function GetClusters() {
  return window['go']['main']['App']['GetClusters']();
}

export function GetGrpcMethods(arg1, arg2) {
  return window['go']['main']['App']['GetGrpcMethods'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RefreshToken() {
  return window['go']['main']['App']['RefreshToken']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectNamespace(arg1) {
  return window['go']['main']['App']['SelectNamespace'](arg1);
}

export function SendGrpcRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendGrpcRequest'](arg1, arg2, arg3, arg4, arg5);
}
