// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function ConnectToCluster(arg1:string):Promise<Array<main.NamespaceInfo>>;

export function DescribeGrpcMethod(arg1:string,arg2:string,arg3:string):Promise<main.MethodInfo>;

export function DisconnectFromCluster():Promise<void>;

export function GenerateRequestSkeleton(arg1:string,arg2:string):Promise<string>;

export function GenerateSampleRequest(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetAccessibleNamespaces():Promise<Array<string>>;

export function GetActiveAuthEndpoint():Promise<main.AuthEndpointInfo>;

export function GetAuthState():Promise<main.AuthState>;

export function GetClusters():Promise<Array<main.ClusterInfo>>;

export function GetGrpcMethods(arg1:string,arg2:string):Promise<Array<string>>;

export function GetLogsFolder():Promise<string>;

export function GetSettings():Promise<config.Config>;

export function IsConnected():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<main.AuthState>;

export function Logout():Promise<void>;

export function OpenLogsFolder():Promise<void>;

export function RefreshToken():Promise<main.AuthState>;

export function ResolveRealm(arg1:string):Promise<string>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SelectNamespace(arg1:string):Promise<Array<main.GrpcServiceInfo>>;

export function SendGrpcRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;
